# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def find_even_fibnums_sum(k):
    fib_numbers = [1, 2]
    for i in range(0, k+1): 
        if fib_numbers[-2] + fib_numbers[-1] > k:
            break
        fib_numbers.append(fib_numbers[-2] + fib_numbers[-1])
    return sum([n for n in fib_numbers if n%2 ==0])

print(find_even_fibnums_sum(4000000))
