// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const rl = require("./readline.js");

rl.question("Please enter a number: ", (answer) => {
    const result = findEvenFibnumsSum(parseInt(answer));
    console.log(`Result: ${ result }`);
    rl.close();
});

findEvenFibnumsSum = (input) => {
    const fibNums = [1, 2];
    [...Array(input).keys()].forEach(int => {
        const nextFibSum = fibNums[fibNums.length - 1] + fibNums[fibNums.length -2]
        if (nextFibSum > input) return;
        fibNums.push(nextFibSum)
    })
    return fibNums.filter(num => num % 2 === 0).reduce((a, b) => a + b, 0)
}